apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1USXhNakUxTWpVeE1sb1hEVE14TVRJeE1URTFNalV4TWxvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnA2Cm95RTV0aEFRTzQwZkVsTy9GaFJsc1R4NmJTOWNVd05jdlg2bVlXN2VXZFRSUmVqUU1wNjJyRnQrNHdTZVBHaHQKUDJ4N2FlSExPZlZmODltS3ZNUXZ5ZkRVU21XSXpQVEFIV2l6K1FncUsvYmRHT3lUb2lFYUR0clNwLzdRNHlCVApDRk9XQSthdm1CS2ExZXl4VTFSa0NYY25UK0UxWDVnb3FxazdzRXRTR1orUDAremV3SFpVa052SUh4MHJFRW5tCk1NaU90Y2swY1FLblkzbU55OGVGU0VtUlVvSlVxQWIyVVdvWlUvQWZlNG5haG41WE8yNTJSQW9jWGVsL3pCMlMKSWw3RTJXaVJvRDhvSTh4QW9TYkd2Zzg3RWMwRU84SktWTzBjc0JFbEY1cWhIdG53Vm1kc1VBZWtzdWlnWUh3egoxaFdXbFF4S05mRm9tSUNEbkU4Q0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSbVBVNHAzNHQ0NWtaUUNXYUt2REFBZUdnL2pqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFKR1J6a2JTRwp2eTdLVWl4bTcxZWZSRzhMdEZGdnVsQkZzVlNKZjJ2dTZKUVhUblJhRDc4aGU1LzdBRXR1Z0lSZVAzU2VrTU1oCkRUVTA4UzRPRDhrVDVpUzM0MFE0TldZVUxxRnpObWQ5a2xGdmRhSGRyTHQ2RCtvTHcyaXFRMit3R0FVRTdabHMKWEFISXZmWU9rNmRuUkhhejFObFdoQjc1QjhodXltNjRhT2pRMHpuc0tTZlFoODNQK25mQkduNUZxQmFZcFJvTwpWSkorc3ZpWGkvUjYyNnRHTWF6Y1lGMDNFWHIxWk41Ym9NUENMa2REbThRNEdka01KZ242YTBYSkN0K3p5YU93CjdEQzBOaU5oeDZtelhSSGhRblpySDlXQ3o3UC9XZFRmbzJYWGhoaWdYV05VKzNXV0tKSE95RGNzeXB3TXNuZlMKd3Z3dWFNUURFWlJWVkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklrMUVVR0ZMYUZwWVZuQm9kVVZOT0Zkbk1VeFpTa2hNTldSMVZGOVFhMmhGYVhGd1JsRkpZVWxOVTNjaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMXhZbTQwWWlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTXpWbU5EZGpaakl0WkRFMU1TMDBNMlJqTFRoak9UY3RNbVUwWlRnNFpUVmpNbVl4SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5XUWJVZ3Jad1ZRdmIzUkwtOGZJMHNudWd6NTdlQkJ1cjFIZzlQNXRyVENCSDQyUnBTSEo2cFFPcTQtQzhqa3NMMzg4NGdqWnFkMDlrVlBxdGt6S3VVaWhWZkhhbDBxdWI3dHdXWkhWXzZCcXZZczU0Z1BNUC03eDUybWtqc1BoYm43VHQzYVBaclU1VmI2NXk1dGxILWpyUXJsTEVOR2dpakJsUDVBMTgyZW9UWk80dTNobnBUTnFEMFFKdndtTTNtdEZQWFRUbXdnZW1wVmNkaWNtcTlvNzdmZy1Oem9MQ0l4TnBNeVFEdXg3ZlFDdTVGRnJuNjh4TFVSaV9OQ3g4MmVLOTZwc3NJMXBCOU0xUkp3Y1gzT0Rkb1pvaTNhdUlYMWxMWjRDUDg5b0paU0pHa2ZuRVdpY3poSi1JdHF3OFVmWENkY2NrT2RKS0dMU21kRk9ORXc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 35f47cf2-d151-43dc-8c97-2e4e88e5c2f1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-12-14T15:13:42Z"
  name: default-token-qbn4b
  namespace: guestbook
type: kubernetes.io/service-account-token
